# This file provides instructions for packaging.

`MooseX-ModifyTaggedMethods`
	perl_version_from m`MooseX::ModifyTaggedMethods`;
	version_from      m`MooseX::ModifyTaggedMethods`;
	readme_from       m`MooseX::ModifyTaggedMethods`;
	test_requires     p`Test::More 0.61`;
	requires          p`Moose 2.00`;
	requires          p`MooseX::RoleQR 0.003`;
	requires          p`match::simple 0.004`;
	test_requires     p`Sub::Talisman 0.002`;
.

